version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: camunda-postgres
    environment:
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda_password
      POSTGRES_DB: camunda_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: